version: '3.8'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - 7700:80
    links:
      - db
  db:
    container_name: db
    image: mysql:5.7
    # image: mariadb:10.5
    restart: always
    env_file:
      - ".env"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql:rw
    ports:
      - 3310:3306
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
        - '8800:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
        - db